fn_args_layout = "Compressed"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Crate"
merge_derives = true
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
